version: "3"

services:
  mysql-dev:
    image: mysql:8.0.2
    container_name: mysql.zigong.docker
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ZIGONG
    ports:
      - "3308:3306"

  postgres:
    image: postgres:latest
    container_name: postgres.zigong.docker
    environment:
      POSTGRES_PASSWORD: password

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher.zigong.docker
    restart: unless-stopped
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:1080:1080
    networks:
      - global

networks:
  global:
    external: true
