"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Files",
      [
        {
          thumbnail: "G1ASjM2JelgQhfROKB6yJTkNj.png",
          name: "zigong-texas-1.png",
          description: null,
          file: "seya9EDRNFuyrMfid1TQ7ZsuS.png",
          mimetype: "png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "4tI5bBvirPi15hcRwKpoJfKF2.png",
          name: "SLIDE5.jpg",
          description: null,
          file: "iZm3ChAxVq4dEH9HxEsOBYpHo.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "M6DxaUDNZiAvcvepMIC6iSiw5.png",
          name: "Slider-wmo.jpg",
          description: null,
          file: "spDudw8tKWKzapw9XUPPbEJaI.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "zzXU0U8vaFNaWi2LALV0oGbHX.png",
          name: "SLIDE1.jpg",
          description: null,
          file: "bj1o1314i7LPDJInsXxpfQ6Tj.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "DS2BbhpV7CJrqeNz1DK25lQPq.png",
          name: "SLIDE2.jpg",
          description: null,
          file: "6u60MeTjB8Mf1XPGVahQrkEoS.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "5MIlZxVytmU89SG2gc2Kc0vEf.png",
          name: "SLIDE3.jpg",
          description: null,
          file: "e1vMFwm4F2u9LZrN64QqdOJe8.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "p3BjYuCXHSay6K41DK56GXzdl.png",
          name: "powders.png",
          description: null,
          file: "HXAsh1iF2NIqEEgnbzblAwvT5.png",
          mimetype: "png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "pgR6FhqvrpDUMUoZoPj0d1GUQ.png",
          name: "products-powders.jpg",
          file: "TGIIzRrwNJsrHFGfSI6fb0Tey.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "GbHZUYNiT9deSyb1Z1AVdtHZl.png",
          name: "2-cemented-carbides-home-page.png",
          file: "TmOenRlsG3rXYocFYJCc8fBUL.png",
          mimetype: "png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "YM1uNmd1HMMXWdGnQiWiwKngG.png",
          name: "products-cemented-carbides.jpg",
          file: "LKFxZ8z2KdWtFFNcRELzsBi3g.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "JuVKAczMrfsfM771kiRcaJVHj.png",
          name: "hard-facing-powder-a.png",
          file: "IMwyLXmvL0e3k6b7VAgyeQ4RO.png",
          mimetype: "png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "X8QhvP2QzYhMkQ3GDC394ZPIL.png",
          name: "products-hardfacing-material.jpg",
          file: "kDOIFsaI6uXOl16OyKZVy2AaI.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "Cn6gNG9yIVWl6neyvOWl2SDyg.png",
          name: "products-wmo-products.jpg",
          file: "3FcxqzrLWqBpNpxFj56Iysch8.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "ia4FfBxFGIR1YpFKtx0dmwKWZ.png",
          name: "w-mo-products-homepage.jpg",
          file: "bRsXuOufbsMWkD5YZkqWZ7mhU.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "uSsfVh7WvxwyVsoDwB4qxEWbd.png",
          name: "equipment-a.png",
          file: "v5srMXejDFsngtGbLtsPKWKe2.png",
          mimetype: "png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          thumbnail: "cTVoneXMLeSNuHIX2sOl6TJ79.png",
          name: "products-equipment.jpg",
          file: "EwKEjNNUSSAJBG97vtFWgzdZA.jpeg",
          mimetype: "jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {},
};
