"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Files",
      [
        {
          thumbnail: "G1ASjM2JelgQhfROKB6yJTkNj.png",
          name: "zigong-texas-1.png",
          description: null,
          file: "seya9EDRNFuyrMfid1TQ7ZsuS.png",
          mimetype: "png",
        },
        {
          thumbnail: "4tI5bBvirPi15hcRwKpoJfKF2.png",
          name: "SLIDE5.jpg",
          description: null,
          file: "iZm3ChAxVq4dEH9HxEsOBYpHo.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "M6DxaUDNZiAvcvepMIC6iSiw5.png",
          name: "Slider-wmo.jpg",
          description: null,
          file: "spDudw8tKWKzapw9XUPPbEJaI.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "zzXU0U8vaFNaWi2LALV0oGbHX.png",
          name: "SLIDE1.jpg",
          description: null,
          file: "bj1o1314i7LPDJInsXxpfQ6Tj.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "DS2BbhpV7CJrqeNz1DK25lQPq.png",
          name: "SLIDE2.jpg",
          description: null,
          file: "6u60MeTjB8Mf1XPGVahQrkEoS.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "5MIlZxVytmU89SG2gc2Kc0vEf.png",
          name: "SLIDE3.jpg",
          description: null,
          file: "e1vMFwm4F2u9LZrN64QqdOJe8.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "p3BjYuCXHSay6K41DK56GXzdl.png",
          name: "powders.png",
          description: null,
          file: "HXAsh1iF2NIqEEgnbzblAwvT5.png",
          mimetype: "png",
        },
        {
          thumbnail: "pgR6FhqvrpDUMUoZoPj0d1GUQ.png",
          name: "products-powders.jpg",
          file: "TGIIzRrwNJsrHFGfSI6fb0Tey.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "GbHZUYNiT9deSyb1Z1AVdtHZl.png",
          name: "2-cemented-carbides-home-page.png",
          file: "TmOenRlsG3rXYocFYJCc8fBUL.png",
          mimetype: "png",
        },
        {
          thumbnail: "YM1uNmd1HMMXWdGnQiWiwKngG.png",
          name: "products-cemented-carbides.jpg",
          file: "LKFxZ8z2KdWtFFNcRELzsBi3g.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "JuVKAczMrfsfM771kiRcaJVHj.png",
          name: "hard-facing-powder-a.png",
          file: "IMwyLXmvL0e3k6b7VAgyeQ4RO.png",
          mimetype: "png",
        },
        {
          thumbnail: "X8QhvP2QzYhMkQ3GDC394ZPIL.png",
          name: "products-hardfacing-material.jpg",
          file: "kDOIFsaI6uXOl16OyKZVy2AaI.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "Cn6gNG9yIVWl6neyvOWl2SDyg.png",
          name: "products-wmo-products.jpg",
          file: "3FcxqzrLWqBpNpxFj56Iysch8.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "ia4FfBxFGIR1YpFKtx0dmwKWZ.png",
          name: "w-mo-products-homepage.jpg",
          file: "bRsXuOufbsMWkD5YZkqWZ7mhU.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "uSsfVh7WvxwyVsoDwB4qxEWbd.png",
          name: "equipment-a.png",
          file: "v5srMXejDFsngtGbLtsPKWKe2.png",
          mimetype: "png",
        },
        {
          thumbnail: "cTVoneXMLeSNuHIX2sOl6TJ79.png",
          name: "products-equipment.jpg",
          file: "EwKEjNNUSSAJBG97vtFWgzdZA.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "zKnzNk4NdVPXZsPlRMLyciell.png",
          name: "pobrane.jpeg",
          file: "muXYiOSIFbnGOplvHROGE0WVF.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "QXNQ8G6SIONhzO6C9sQdLEPZY.png",
          name: "pobrane (1).jpeg",
          file: "nkmHixBTYe4WYWpZZwXz2lHZr.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "2VQFv6crxewmNG6QeahjpiiOK.png",
          name: "pobrane (2).jpeg",
          file: "vBWYwZFmVkF8yuZJFYN5IYGkW.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "nxuFMFi6BhGHGrQnkfX4QbO1K.png",
          name: "pobrane (3).jpeg",
          file: "DsZJSqLPOBD6IpnvJQQNT9oPY.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "0eD2nz5MGIOwCIJTs8iBbZnNZ.png",
          name: "pobrane (1).jpeg",
          file: "MaC2A5L4WSK1vkxXHfXyyTOvg.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "iCYM2zE9Gf2wYANU0QBRZwvIF.png",
          name: "pobrane (2).jpeg",
          file: "0NeOUqAQtHXaIh19hTF15myzO.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "sNXEkQrEZcWhowYhJ3wD3Q0sj.png",
          name: "pobrane (3).jpeg",
          file: "Oi27eIf51BD1yJerU6XV9pF8d.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "FGgbwsGiTqIF5G5iUrXmcoRN2.png",
          name: "pobrane (4).jpeg",
          file: "wm282jpArZmFBR1rOay701gXj.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "hs4ytt8R4yZWhwenA8fEw3rBS.png",
          name: "pobrane (5).jpeg",
          file: "9USPWJ0fLoTVXjylQUN8ec8Hh.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "i2Udl04q0Gxi9rT6xVyahGZhV.png",
          name: "pobrane (6).jpeg",
          file: "SM7MiX1jvqdClyll5HWZ9Eo3k.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "eWcvUuZ7Ck5nYcTwTjo54IoNt.png",
          name: "pobrane (7).jpeg",
          file: "7kuZrYN2ZJa3zv8ArnebP0YjH.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "IpLQaObCrXBZJ34vrqN9aZfbW.png",
          name: "pobrane (8).jpeg",
          file: "rCrTtH00o7jX9z33ZJknJRcfD.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "EYWpzlJo6tK6cN3RcakpWk0br.png",
          name: "pobrane.jpeg",
          file: "uXAHiYZlEnjOwiNUC5FE4wBYX.jpeg",
          mimetype: "jpeg",
        },
        {
          thumbnail: "hnJbTg33RBpgMhtQ5qd4YpiYl.png",
          name: "CNAS-1-1.pdf",
          description: "CNAS",
          file: "JGzM98fs0qrxXItGTcpnLFpng.pdf",
          mimetype: "pdf",
        },
        {
          thumbnail: "gZruu7TmZgpBEXfX5eHiW7aJj.png",
          name: "ISO-9001-1.pdf",
          description: "ISO-9001",
          file: "M3bSlHoZ1fqOzpppIiVrv7fro.pdf",
          mimetype: "pdf",
        },
        {
          thumbnail: "Y1ehJrAY4BWnwFKogsOh9l2tF.png",
          name: "ISO-14001-2.pdf",
          description: "ISO-14001",
          file: "tLRAJWlqmzOXYsGi6wETDZF2Q.pdf",
          mimetype: "pdf",
        },
        {
          thumbnail: "gIdWVSS72WuU2qyHlZfN04pda.png",
          name: "ISO-45001-1.pdf",
          description: "ISO-45001",
          file: "5I3mLvVmTDx5MO52vQ1F9ptzi.pdf",
          mimetype: "pdf",
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {},
};
